name: data
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./postprocessing/prefecture.js
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://vrs-data.cio.go.jp/vaccination/opendata/latest/prefecture.ndjson
          downloaded_filename: ./prefecture.ndjson
          postprocess: ./postprocessing/prefecture.js
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://vrs-data.cio.go.jp/vaccination/opendata/latest/summary_by_date.csv
          downloaded_filename: ./summary_by_date.csv
